### ISSUE TITLE
DLE server session.json file empty after restart

### ISSUE THREAD

**Issue by ypadlyak** [postgres-ai/database-lab-engine#155]
DLE server session file empty after restart. I have noticed it two times already. Had to recreate instance. Is there are any way to debug it?

**Comment by agneum** [comment]
@ypadlyak Thanks for the report. 

Usually the problem can be seen in the logs with the debug mode enabled. It is worth paying attention to the entries when stopping and starting the container.

I would also recommend checking volume monitoring

**Comment by vitabaks** [comment]
I am closing this issue as it no longer appears relevant. If this is not the case, feel free to reopen it.
