### ISSUE TITLE
Documentation update and add some usefull info

### ISSUE THREAD

**Issue by byx01** [postgres-ai/database-lab-engine#167]
Hello! 
1) Please update https://postgres.ai/docs/questions-and-answers#what-do-i-need-to-use-database-lab as it now possible to use not only another zfs pool, but also zfs dataset
2) If possible , please add in docs (may be in Tutorial or may be server.yml) some rows how to use several DLE's оn one host ( how to add zfs pool dataset to MounDir , etc) . It was quite difficult to understand for the first time that zfs datasets can be mounted near current zfs pool in MountDir).
thanks

**Comment by NikolayS** [comment]
@byx01 thanks for these requests

1 – will definitely do (but MRs are also welcome, the docs are open too)
2 – might do as well, but this is a lower priority (though again, will be happy to review and accept MR proposals)

**Comment by vitabaks** [comment]
I am closing this issue as it no longer appears relevant. If this is not the case, feel free to reopen it.
