### ISSUE TITLE
after application of MR 188, jobs always starting after DLE restart 

### ISSUE THREAD

**Issue by terem42** [postgres-ai/database-lab-engine#22]
Tested AWS with logical cloning of PR 188 and saving dblab state to file if container is restarted. It works, but for some reason logicalDump/Restore jobs are started too.
As a result, every time after dle restart, a new snapshot is created, which is unacceptable. Possible fix should add a setting to skip these jobs start, if clones for this snapshot already exist.

**Comment by vitabaks** [comment]
I am closing this issue as it no longer appears relevant. If this is not the case, feel free to reopen it.
