### ISSUE TITLE
DLE instance DNS record broken after instance stop/start needed to change intance size

### ISSUE THREAD

**Issue by ypadlyak** [postgres-ai/database-lab-engine#90]
additional Elastic IP should be introduced in TF templates

**Comment by anatolystansler** [comment]
Hi @ypadlyak, could you please provide a step-by-step guide to reproduce the error?

**Comment by ypadlyak** [comment]
But first, you must stop Putin, as he is killing us here in Ukraine as we speak. Running to the basement with my family and my 1y.o. daughter every now and then here in Lviv on air raid sirens. In other cities, there are rocket strikes killing civilians happening around the clock. Check it out here: https://t.me/UkraineNow, there are russians speaking. This is happening Kharkiv today: https://t.me/UkraineNow/3240

**Comment by NikolayS** [comment]
@ypadlyak hi, Postgres.ai founder here.

What's happening right now is absolutely terrible, it is, by all means, a crime against the world, humanity.

We're on your side, fighting with Putin's criminal regime (and it hasn't started last week, but now it's black and white, no more half-tones).

Please, stay strong and safe ❤️

**Comment by vitabaks** [comment]
I am closing this issue as it no longer appears relevant. If this is not the case, feel free to reopen it.
